# Generated by Django 5.1.5 on 2025-01-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('flag', models.URLField(blank=True, max_length=255)),
                ('sync_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookmaker', models.CharField(max_length=255)),
                ('odds', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('logo', models.URLField(blank=True, max_length=255)),
                ('sync_on', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.country')),
                ('group', models.ManyToManyField(to='extractor.group')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('start', models.DateField(blank=True)),
                ('end', models.DateField(blank=True)),
                ('current', models.BooleanField(default=False)),
                ('coverage', models.JSONField()),
                ('sync_on', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.league')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('national', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.country')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('periods', models.JSONField()),
                ('status', models.JSONField()),
                ('home_goals', models.IntegerField(null=True)),
                ('away_goals', models.IntegerField(null=True)),
                ('score', models.JSONField()),
                ('rf_prediction', models.FloatField(null=True)),
                ('model_predictions', models.JSONField(default=dict, null=True)),
                ('home_favor_goals_avg', models.FloatField(null=True)),
                ('home_against_goals_avg', models.FloatField(null=True)),
                ('away_favor_goals_avg', models.FloatField(null=True)),
                ('away_against_goals_avg', models.FloatField(null=True)),
                ('home_league_goals_avg', models.FloatField(null=True)),
                ('away_league_goals_avg', models.FloatField(null=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.league')),
                ('odds', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.odds')),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away', to='extractor.team')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home', to='extractor.team')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.venue')),
            ],
        ),
    ]
