# Generated by Django 5.1.5 on 2025-01-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_bet_bookmaker_odds_bet_alter_odds_bookmaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='sync_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='sync_on',
            field=models.BooleanField(default=False),
        ),
    ]
