# Generated by Django 5.1.5 on 2025-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_alter_country_flag_alter_team_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
