# Generated by Django 5.1.5 on 2025-08-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_alter_venue_address_alter_venue_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
