# Generated by Django 5.1.5 on 2025-09-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_alter_venue_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.venue'),
        ),
    ]
