# Generated by Django 5.1.5 on 2025-09-18 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0009_alter_team_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_shots_on_goal', models.IntegerField(null=True)),
                ('away_shots_on_goal', models.IntegerField(null=True)),
                ('home_shots_off_goal', models.IntegerField(null=True)),
                ('away_shots_off_goal', models.IntegerField(null=True)),
                ('home_total_shots', models.IntegerField(null=True)),
                ('away_total_shots', models.IntegerField(null=True)),
                ('home_blocked_shots', models.IntegerField(null=True)),
                ('away_blocked_shots', models.IntegerField(null=True)),
                ('home_shots_inside_box', models.IntegerField(null=True)),
                ('away_shots_inside_box', models.IntegerField(null=True)),
                ('home_shots_outside_box', models.IntegerField(null=True)),
                ('away_shots_outside_box', models.IntegerField(null=True)),
                ('home_fouls', models.IntegerField(null=True)),
                ('away_fouls', models.IntegerField(null=True)),
                ('home_corners', models.IntegerField(null=True)),
                ('away_corners', models.IntegerField(null=True)),
                ('home_offsides', models.IntegerField(null=True)),
                ('away_offsides', models.IntegerField(null=True)),
                ('home_ball_possession', models.IntegerField(null=True)),
                ('away_ball_possession', models.IntegerField(null=True)),
                ('home_yellow_cards', models.IntegerField(null=True)),
                ('away_yellow_cards', models.IntegerField(null=True)),
                ('home_red_cards', models.IntegerField(null=True)),
                ('away_red_cards', models.IntegerField(null=True)),
                ('home_goalkeeper_saves', models.IntegerField(null=True)),
                ('away_goalkeeper_saves', models.IntegerField(null=True)),
                ('home_total_passes', models.IntegerField(null=True)),
                ('away_total_passes', models.IntegerField(null=True)),
                ('home_passes_accurate', models.IntegerField(null=True)),
                ('away_passes_accurate', models.IntegerField(null=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extractor.fixture')),
            ],
        ),
    ]
