# Generated by Django 6.0 on 2025-12-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0018_oddvalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odds',
            name='odds',
        ),
    ]
