# Generated by Django 6.0 on 2025-12-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0020_alter_odds_id_alter_oddvalues_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetParameter',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('field', models.CharField(blank=True, max_length=32)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.bet')),
            ],
        ),
    ]
