# Generated by Django 6.0 on 2025-12-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0021_betparameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betparameter',
            old_name='field',
            new_name='prob_name',
        ),
        migrations.AddField(
            model_name='betparameter',
            name='bookmaker',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='extractor.bookmaker'),
            preserve_default=False,
        ),
    ]
