# Generated by Django 6.0 on 2025-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0022_rename_field_betparameter_prob_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddvalues',
            name='prob_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
