# Generated by Django 6.0 on 2025-12-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0023_oddvalues_prob_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='odds',
            name='prob_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='BetParameter',
        ),
    ]
