# Generated by Django 6.0 on 2025-12-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0025_remove_odds_prob_name_betparameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betparameter',
            old_name='name',
            new_name='key',
        ),
    ]
