# Generated by Django 6.0 on 2025-12-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0027_fixture_away_n_fixture_home_n_fixture_league_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='betparameter',
            name='threshold',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
