# Generated by Django 6.0 on 2025-12-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0028_betparameter_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betparameter',
            name='threshold',
            field=models.FloatField(default=0),
        ),
    ]
