# Generated by Django 6.0 on 2025-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0031_remove_betparameter_bookmaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
