# Generated by Django 6.0 on 2026-01-16 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0033_alter_season_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBetItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('fixed_value', models.BooleanField(default=False)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.fixture')),
                ('odd_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.oddvalues')),
                ('userbet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.userbets')),
            ],
        ),
    ]
