# Generated by Django 5.1.5 on 2025-01-21 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookMaker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='odds',
            name='bet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='extractor.bet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='odds',
            name='bookmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.bookmaker'),
        ),
    ]
