# Generated by Django 5.1.5 on 2025-01-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_remove_fixture_league_remove_fixture_rf_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='surface',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
