# Generated by Django 5.1.5 on 2025-08-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_alter_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='surface',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
