# Generated by Django 5.1.5 on 2025-09-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0013_rename_account_userconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='updated_at',
        ),
    ]
