# Generated by Django 6.0 on 2025-12-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0014_remove_userconfig_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
