# Generated by Django 6.0 on 2025-12-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0015_bet_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='odds',
        ),
        migrations.AddField(
            model_name='odds',
            name='fixture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extractor.fixture'),
        ),
    ]
