# Generated by Django 6.0 on 2025-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0016_remove_fixture_odds_odds_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odds',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
