# Generated by Django 6.0 on 2025-12-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0017_alter_odds_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.odds')),
            ],
        ),
    ]
