# Generated by Django 6.0 on 2025-12-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0019_remove_odds_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odds',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oddvalues',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
