# Generated by Django 6.0 on 2025-12-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0024_odds_prob_name_delete_betparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odds',
            name='prob_name',
        ),
        migrations.CreateModel(
            name='BetParameter',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('prob_name', models.CharField(blank=True, max_length=32)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.bet')),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.bookmaker')),
            ],
        ),
    ]
