# Generated by Django 6.0 on 2025-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0026_rename_name_betparameter_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_n',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_n',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='league_n',
            field=models.FloatField(null=True),
        ),
    ]
