# Generated by Django 6.0 on 2025-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0029_alter_betparameter_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
