# Generated by Django 6.0 on 2025-12-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0030_alter_season_end_alter_season_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betparameter',
            name='bookmaker',
        ),
    ]
