# Generated by Django 6.0 on 2025-12-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0032_alter_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
